providers:
  docker:
    endpoint: "tcp://docker-proxy:2375"
    exposedByDefault: false
    network: "housekpr-network"
  file:
    directory: "/etc/traefik/rules"

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsEncrypt

certificatesResolvers:
  letsEncrypt:
    acme:
      email: e.lobanovsky@yandex.ru
      storage: acme.json
      httpChallenge:
        entryPoint: http

log:
  level: INFO
